apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
  namespace: api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - name: account
          image: collins/account
          envFrom:
            - configMapRef:
                name: account-config
            - secretRef:
                name: account-secret
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: account-srv
  namespace: api
  labels:
    app: account

spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: account
