apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq
          ports:
            - containerPort: 5672
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-srv
  namespace: api
  labels:
    app: rabbitmq

spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq
